Update functions
nina-protocol/js-sdk pull request #18
Opened 2023-05-18 20:36 UTC by ikjudd

- [ ] refactored `wallet` and `connection ` params, pulling them off of the `client.provider` object
- [ ] reassigned `program` var in each function to `await client.useProgram()`
- [ ] updated logic in `hubs.js` to match logic of current working `nina-internal-sdk` and accommodate magic wallets
- [ ] updated logic in `releaseCreate` and `releaseInitViaHub` in `release.js` to match logic of current working `nina-internal-sdk` and accommodate magic wallets

2023-05-26 20:53 UTC, ejf89 commented on package.json
> +  "version": "0.0.14",
should be updated to `0.0.18`

2023-05-26 20:59 UTC, ejf89 commented on src/resources/exchanges.js
> +    return txid;
should return object of accepted exchange

2023-05-26 21:00 UTC, ejf89 commented on src/resources/exchanges.js
> +    exchangePubkey,
inconsistent return values

2023-05-26 21:06 UTC, ejf89 commented on src/resources/hubs.js
> +    // const collaborator = await fetchHubCollaborator(hub.handle, collaboratorPubkey.toBase58());
should return `hubCollaborator`

2023-05-26 21:06 UTC, ejf89 commented on src/resources/hubs.js
> +    // const collaborator = await fetchHubCollaborator(hub.handle, collaboratorPubkey.toBase58());
shoudl return `hubCollaborator`

2023-05-26 21:06 UTC, ejf89 commented on src/resources/hubs.js
> +    // const collaborator = await fetchHubCollaborator(hub.handle, collaboratorPubkey.toBase58());
should return hubCollaborator

2023-05-26 21:09 UTC, ejf89 commented on src/resources/releases.js
> +    return txid;
shoudl return release

2023-05-26 21:09 UTC, ejf89 commented on src/resources/releases.js
> +    return txid;
should return release

2023-05-26 21:11 UTC, ejf89 commented on src/resources/releases.js
> +    return recipientPublicKey;
insonsistent return values

2023-05-26 21:11 UTC, ejf89 commented on src/utils.js
> +        // new anchor.web3.PublicKey('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v')
should not be here

2023-05-26 21:12 UTC, ejf89 requested changes
functions should return the resource that is relevant to the function.
JSdoc snippets should reflect that.

2023-05-26 21:12 UTC, ejf89 requested changes
functions should return the resource that is relevant to the function.
JSdoc snippets should reflect that.

2023-06-01 17:32 UTC, ikjudd commented
this pass of updates to the repo focused on creating consistent return values. returning objects instead of strings
ex. `return { release: newReleaseData }`

2023-06-01 18:39 UTC, ikjudd commented
merged `clean-up` branch into `update-functions`

2023-06-02 15:02 UTC, facing-n requested changes

2023-06-02 15:02 UTC, facing-n commented on src/client.js
> +import Nina from '.';
is this used anywhere?

2023-06-02 15:02 UTC, facing-n commented on src/resources/subscriptions.js
> +  subscriptionData: subscriptionData,
return prop should be called name of resource it is returning - so here `subscription`

2023-06-02 15:02 UTC, facing-n commented on src/resources/subscriptions.js
> +      subscriptionData: subscriptionData,
`subscription`

2023-06-06 16:06 UTC, ejf89 approved these changes

2023-06-06 16:06 UTC, merged